apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Apply the infrastructure Kustomization first
  - infrastructure.yaml
  # Then apply apps etc.
  - apps/tailscale
  - apps/n8n
  - apps/homer
  - core/dns-config
  - apps/postgresql
  - apps/monitoring
