apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure
  - apps/tailscale
  - apps/home-assistant
  - apps/immich
  - apps/n8n
  - apps/owncloud
  - apps/glance
  - apps/homer
  - core/dns-config
  - apps/postgresql
  - apps/monitoring
