apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Apply the Kustomizations that manage infrastructure and apps
  - infrastructure.yaml
  - apps.yaml
  # We will also apply the flux-system manifests from here
  - flux-system/gotk-sync.yaml