apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: leantime # Set the namespace for resources in this kustomization
resources:
  - namespace.yaml
  - sealed-secret.yaml # Apply the secret first
  - deployment.yaml
  - service.yaml
  - ingress.yaml
