apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance
  namespace: glance
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: glance-glance-strip-prefix@kubernetescrd,glance-glance-add-prefix-for-redirects@kubernetescrd
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
  - hosts:
    - asuna.chimp-ulmer.ts.net
    secretName: glance-tls
  rules:
  - host: asuna.chimp-ulmer.ts.net
    http:
      paths:
      - path: /glance
        pathType: Prefix
        backend:
          service:
            name: glance
            port:
              number: 8080
