apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - configmap-script.yaml
  - configmap-nginx.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingress.yaml
