apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  namespace: owncloud
  labels:
    app: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
        - name: owncloud
          image: owncloud/server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: OWNCLOUD_ADMIN_USERNAME
              value: "admin"
            - name: OWNCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-secret
                  key: password
            - name: OWNCLOUD_MYSQL_HOST
              value: "owncloud-mariadb"
            - name: OWNCLOUD_MYSQL_PORT
              value: "3306"
            - name: OWNCLOUD_MYSQL_DATABASE
              value: "owncloud"
            - name: OWNCLOUD_MYSQL_USERNAME
              value: "owncloud"
            - name: OWNCLOUD_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-mariadb-secret
                  key: password
            - name: OWNCLOUD_DOMAIN
              value: "owncloud.app.pesulabs.net"
            - name: OWNCLOUD_TRUSTED_DOMAINS
              value: "owncloud.app.pesulabs.net"
            - name: OWNCLOUD_TRUSTED_PROXIES
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            - name: OWNCLOUD_OVERWRITE_WEBROOT
              value: ""
            - name: OWNCLOUD_OVERWRITE_PROTOCOL
              value: "https"
            - name: OWNCLOUD_OVERWRITE_HOST
              value: "owncloud.app.pesulabs.net"
            - name: OWNCLOUD_OVERWRITE_CLI_URL
              value: "https://owncloud.app.pesulabs.net"
            - name: OWNCLOUD_OVERWRITE_COND_ADDR
              value: "^10\\.42\\..*"
          volumeMounts:
            - mountPath: /mnt/data
              name: owncloud-data
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
      volumes:
        - name: owncloud-data
          persistentVolumeClaim:
            claimName: owncloud-data
---
apiVersion: v1
kind: Service
metadata:
  name: owncloud
  namespace: owncloud
  labels:
    app: owncloud
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: owncloud
