apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owncloud
  namespace: owncloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: "owncloud.app.pesulabs.net"
spec:
  tls:
  - hosts:
    - owncloud.app.pesulabs.net
    secretName: owncloud-tls
  rules:
    - host: owncloud.app.pesulabs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: owncloud
                port:
                  number: 80
