apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - persistent-volume-claims.yaml
  - middleware.yaml
  - ingress.yaml
  - deployment.yaml
  - secrets.yaml
  - mariadb.yaml
