apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Order matters: Apply sources first, then monitoring, then cert-manager
  - sources
  - monitoring
  - networking
  - cert-manager.yaml
  - cert-manager-resources.yaml
  - local-dns
