apiVersion: v1
kind: Service
metadata:
  name: family-assistant
  namespace: homelab
  labels:
    app: family-assistant
    component: backend-alias
spec:
  type: ClusterIP
  ports:
    - name: http-api
      port: 8001
      targetPort: 8001
      protocol: TCP
  selector:
    app: family-assistant-backend
    component: familyai-v3
