model_list:
  - model_name: llama3
    litellm_params:
      model: ollama/llama3.2
      api_base: http://192.168.1.10:11434
      
  - model_name: mistral
    litellm_params:
      model: ollama/mistral
      api_base: http://192.168.1.10:11434

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  timeout: 300
