model_list:
  - model_name: llama3
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://127.0.0.1:11434

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  timeout: 300
