apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: home-assistant-home-assistant-strip-prefix@kubernetescrd,home-assistant-home-assistant-headers@kubernetescrd
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
  - hosts:
    - asuna.chimp-ulmer.ts.net
    secretName: home-assistant-tls
  rules:
  - host: asuna.chimp-ulmer.ts.net
    http:
      paths:
      - path: /home-assistant
        pathType: Prefix
        backend:
          service:
            name: home-assistant
            port:
              number: 8123
