apiVersion: v1
kind: Service
metadata:
  name: llamacpp-kimi-vl-service
  namespace: llamacpp
  labels:
    app.kubernetes.io/name: llamacpp
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: kimi-vl
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: http
    nodePort: 30180
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: llamacpp
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: kimi-vl