apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: APP_NAME
  namespace: APP_NAME
  annotations:
    # Add app-specific annotations here
    # nginx.ingress.kubernetes.io/proxy-body-size: "64m"
spec:
  rules:
  - host: APP_NAME.asuna.chimp-ulmer.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: APP_NAME
            port:
              number: 80
