apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: APP_NAME
  namespace: APP_NAME
  annotations:
    # Add app-specific annotations here
    # nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: asuna.chimp-ulmer.ts.net
    http:
      paths:
      - path: /APP_NAME(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: APP_NAME
            port:
              number: 80
