apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: homer
data:
  traefik.yaml: |
    http:
      routers:
        dashboard:
          rule: "PathPrefix(`/`)"
          service: files
      services:
        files:
          loadBalancer:
            servers:
              - url: "file:///var/www/"
