apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgresql
  namespace: database
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: postgresql.app.pesulabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: postgresql
            port:
              number: 5432
  tls:
  - hosts:
    - postgresql.app.pesulabs.net
