apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: family-assistant-ingress
  namespace: homelab
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - "family-assistant.homelab.pesulabs.net"
  rules:
  - host: "family-assistant.homelab.pesulabs.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: family-assistant
            port:
              number: 8001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery-dashboard-ingress
  namespace: homelab
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - "discover.homelab.pesulabs.net"
  rules:
  - host: "discover.homelab.pesulabs.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: discovery-dashboard
            port:
              number: 80
