apiVersion: v1
kind: ConfigMap
metadata:
  name: external-coredns-config
  namespace: local-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        forward . 8.8.8.8 8.8.4.4
        cache 30
        loop
        reload
        loadbalance
    }
    
    cluster.local:53 {
        errors
        cache 30
        forward . 10.43.0.10
        reload
    }
    
    svc.cluster.local:53 {
        errors
        cache 30
        forward . 10.43.0.10
        reload
    }
