apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - release.yaml
  - clusterissuer.yaml
secretGenerator:
  - name: cloudflare-api-token
    type: Opaque
    literals:
      - api-token=QIgulCkm6_yRAlpozQ4PlKIpDgj82W5TusFdu4hI
