apiVersion: v1
kind: Namespace
metadata:
  name: family-assistant-app
  labels:
    name: family-assistant-app
    app.kubernetes.io/name: family-assistant-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: homelab