apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-secret.yaml # Add sealed secret
  - pvc.yaml
  - deployment.yaml
  - rbac.yaml
  - hybrid-services
  - dns-sharing.yaml
