apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx # Standard namespace for nginx-ingress
resources:
  # We will add the downloaded deploy.yaml here
  - deploy.yaml