apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - port: 8096
    name: web
    targetPort: web
  - port: 8920
    name: https
    targetPort: https
  - port: 7359
    name: discovery
    protocol: UDP
    targetPort: discovery
  - port: 1900
    name: dlna
    protocol: UDP
    targetPort: dlna
