apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - namespace.yaml
  - helmrepository.yaml
  - release.yaml

secretGenerator:
  - name: cloudflare-api-token
    type: Opaque
    literals:
      - api-token=REPLACE_WITH_YOUR_ACTUAL_TOKEN
