apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: local-dns
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        hosts {
            192.168.86.141 homer.app.pesulabs.net
            192.168.86.141 immich.app.pesulabs.net
            192.168.86.141 grafana.app.pesulabs.net
            192.168.86.141 prometheus.app.pesulabs.net
            192.168.86.141 home-assistant.app.pesulabs.net
            192.168.86.141 n8n.app.pesulabs.net
            192.168.86.141 owncloud.app.pesulabs.net
            192.168.86.141 glance.app.pesulabs.net
            192.168.86.141 qdrant.app.pesulabs.net
            fallthrough
        }
        template IN A app.pesulabs.net {
            answer "{{ .Name }} 60 IN A 192.168.86.141"
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4 {
            max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
