apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Apply namespace first, then the full deployment manifest
resources:
  - namespace.yaml
  - deploy.yaml # Apply the downloaded manifest
