apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  namespace: immich
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    external-dns.alpha.kubernetes.io/hostname: "immich.app.pesulabs.net"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50G"
spec:
  tls:
  - hosts:
    - immich.app.pesulabs.net
    secretName: immich-tls
  rules:
  - host: immich.app.pesulabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-web
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: immich-server
            port:
              number: 3001
