apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - persistent-volume-claims.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - server.yaml
  - microservices.yaml
  - machine-learning.yaml
  - web.yaml
  - middleware.yaml
  - ingress.yaml
