apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Centralized Helm repository sources
  - bitnami-repo.yaml
  - ingress-nginx-repo.yaml
  - jetstack-repo.yaml
  - prometheus-community-repo.yaml
