apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-pvc.yaml
  - grafana-datasources.yaml
  - grafana-dashboards.yaml
  - grafana-k8s-dashboards.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-ingress.yaml
  - prometheus-pvc.yaml
  - prometheus-configmap.yaml
  - prometheus-rbac.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-ingress.yaml
  - loki-config.yaml
  - loki-pvc.yaml
  - loki-deployment.yaml
  - loki-service.yaml
  - promtail-config.yaml
  - promtail-rbac.yaml
  - promtail-daemonset.yaml
  - kube-state-metrics
  - node-exporter.yaml

patchesStrategicMerge:
  - prometheus-config-update.yaml
