apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  selector:
    app: plex
  ports:
  - port: 32400
    targetPort: 32400
    name: web
  - port: 1900
    targetPort: 1900
    protocol: UDP
    name: dlna
  - port: 3005
    targetPort: 3005
    name: companion
  - port: 5353
    targetPort: 5353
    protocol: UDP
    name: bonjour
  - port: 8324
    targetPort: 8324
    name: roku
  - port: 32410
    targetPort: 32410
    protocol: UDP
    name: gdm1
  - port: 32412
    targetPort: 32412
    protocol: UDP
    name: gdm2
  - port: 32413
    targetPort: 32413
    protocol: UDP
    name: gdm3
  - port: 32414
    targetPort: 32414
    protocol: UDP
    name: gdm4
  type: ClusterIP
